### ISSUE TITLE
Scan error: handling empty arrays

### ISSUE THREAD

**Issue by merefield** [uptrace/bun#5]
Thanks for all your work on this 👍 

Are `uuid` arrays supported, and if so how?

I'm trying to migrate from `github.com/go-pg/pg` which was quite fine with the following go `user` Model element:

```
	FollowedGroups         []uuid.UUID `sql:",type:uuid[]" pg:",array"`
```

I've migrated this to:

```
	FollowedGroups         []uuid.UUID `bun:",type:uuid[],array"`
```

Migration appears successfully setting this field in Postgres table up as:

```
    followed_groups uuid[],
```

Upon attempting to select the table records with bun:

```
	dberr := s.db.NewSelect().
		Model(&users).
		Scan(ctx)
```

I'm getting:

```
sql: Scan error on column index 8, name "followed_groups": bun: got <nil>, wanted []byte or string"
```

Updating value to `{}` manually in pgAdmin leads to:

```
sql: Scan error on column index 8, name \"followed_groups\": json: cannot unmarshal object into Go value of type []string
```

Updating to example data, e..g `{d8014c4e-7c90-42a4-bd1f-2ebd7ccb4545,d8014c4e-7c90-42a4-bd1f-2ebd7ccb4545}` leads to:

```
sql: Scan error on column index 8, name \"followed_groups\": invalid character 'd' looking for beginning of object key string",
```

Exclude this field with a `Column` statement and the query works.

**Comment by vmihailenco** [comment]
Should be fixed in v0.1.10. `bun:",type:uuid[],array"` should be working now.

**Comment by merefield** [comment]
Thanks!  I've updated to v0.1.10, dropped the database, recreated.

However, with:
```
bun:",type:uuid[],array"
```
i'm now getting:
```
panic: pgdialect: []uuid.UUID is not supported
```
If I simplify to:
```
FollowedGroups         []uuid.UUID `bun:",type:uuid[]"`
```
It goes through OK, and I can query the field so long as it is empty.

Unfortunately, if I put in some example data:

```
{d8014c4e-7c90-42a4-bd1f-2ebd7ccb4545,d8014c4e-7c90-42a4-bd1f-2ebd7ccb4545}
```
I still get:

```
sql: Scan error on column index 8, name \"followed_groups\": invalid character 'd' looking for beginning of object key string
```

**Comment by vmihailenco** [comment]
@merefield are you sure you've updated pgdialect as well? You should bump all bun dependencies together. I usually go to go.mod and bump all bun related packages

```
	github.com/uptrace/bun v0.1.11
	github.com/uptrace/bun/dialect/pgdialect v0.1.11
	github.com/uptrace/bun/driver/pgdriver v0.1.11
	github.com/uptrace/bun/extra/bundebug v0.1.11
	github.com/uptrace/bun/extra/bunotel v0.1.11
```

>If I simplify to:

Without the `array` option Bun tries to decode the column as JSON. That is not what you want.

**Comment by merefield** [comment]
That was part of the problem 👍, the unsupported error has gone away, apologies, all up-to-date now, thanks for your patience.

However, I'm still suffering the issue with the scan:

```
sql: Scan error on column index 8, name \"followed_groups\": invalid character 'd' looking for beginning of object key string
```

It seems to be treating it as json, not an array?:

```
{d8014c4e-7c90-42a4-bd1f-2ebd7ccb4545,d8014c4e-7c90-42a4-bd1f-2ebd7ccb4545}
```

**Comment by vmihailenco** [comment]
This seems to be working fine in tests - https://github.com/uptrace/bun/blob/master/internal/dbtest/pg_test.go#L173-L201. Can you provide a reproducer?

>It seems to be treating it as json, not an array?

Yep, can't tell why. The tag should contain `array` to work properly: `bun:"type:uuid[],array"`

**Comment by merefield** [comment]
My apologies, the model I was inadvertently using was the Protobuf definition, which has this field down as a json field.  Switching to the internal model and then converting types solves the remaining issues!  Thanks for your time, patience and the library!
